In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('Phishing_Email.csv')
df.head()

,Unnamed: 0,Email Text,Email Type
0,0,"re : 6 . 1100 , disc : uniformitarianism , re ...",Safe Email
1,1,the other side of * galicismos * * galicismo *...,Safe Email
2,2,re : equistar deal tickets are you still avail...,Safe Email
3,3,\nHello I am your hot lil horny toy.\n I am...,Phishing Email
4,4,software at incredibly low prices ( 86 % lower...,Phishing Email

In [5]:
df = df.drop(columns=['Unnamed: 0'],errors='ignore')

In [6]:
df.head()

                                          Email Text      Email Type
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email
1  the other side of * galicismos * * galicismo *...      Safe Email
2  re : equistar deal tickets are you still avail...      Safe Email
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email
4  software at incredibly low prices ( 86 % lower...  Phishing Email

In [7]:
print(df.columns)

Index(['Email Text', 'Email Type'], dtype='object')

In [8]:
df = df.dropna(subset=['Email Text'])

In [9]:
df["Label"] = df['Email Type'].map({"Safe Email":0,"Phishing Email":1})

In [10]:
print(df.head())

                                          Email Text      Email Type  Label
0  re : 6 . 1100 , disc : uniformitarianism , re ...      Safe Email      0
1  the other side of * galicismos * * galicismo *...      Safe Email      0
2  re : equistar deal tickets are you still avail...      Safe Email      0
3  \nHello I am your hot lil horny toy.\n    I am...  Phishing Email      1
4  software at incredibly low prices ( 86 % lower...  Phishing Email      1

In [11]:
print(df["Label"].value_counts())

Label
0    11322
1     7312
Name: count, dtype: int64

In [12]:
df.to_csv('Cleaned_Phishing_Email.csv', index=False)